---
- hosts: db
  vars_files:
    - secrets.yml
  tasks:
    - name: Copying MariaDB Repositories
      #Becomes root. Root permissions : "rw", Users and group: "r"
      become: yes 
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
      
    - name : Installing and Updating MariaDB/Client
      #Becomes root
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present

    - name: Copying new MariaDB_Answers.txt
      #Changes mariadb_answers.txt permission to Root:"rw" User and Group:"r"
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644
    - name: Extracting db.tgz to ~/
      unarchive: src=db/db.tgz dest=~/ mode=0755
 
    - name: Making Database and changing directory
      command: ./make_databases.sh {{ db_password }} rds.cv04whytaguq.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
